baseurl: "" # the subpath of your site, e.g. /blog
url: "http://my-portfolio-175.netlify.com/" # the base hostname & protocol for your site


twitter_username: RickBacci_175
github_username:  rickbacci

# Site settings
title: My path to Awesome!
email: rickbacci@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ricky Bacci portfolio awesome ruby rails full stack developer javascript
  jQuery
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: E74C3C
  secondary: ff0000
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rickbacci_175
  - title: github
    url: http://github.com/rickbacci
  - title: linkedin
    url: http://linkedin.com/in/rickbacci

# Postal address (add as many lines as necessary)
address:
  - line: Cleveland, OH 44125

# Build settings
markdown: kramdown
permalink: pretty
